### ISSUE TITLE
Win-Git-Bash

### ISSUE THREAD

**Issue by nhrones** [Im-Beast/deno_tui#26]
The docs recommend WSL for Windows users.
I don't use WSL, but Git for Windows, installs GIT-bash, and this works very well for me.  
You might want to test this first, and then offer that advice in the docs.
Also, it's easy to make GIT-bash the default terminal in VS Code.

**Comment by Im-Beast** [comment]
I'll check it tommorow

**Comment by Im-Beast** [comment]
I've tested it on Windows 11 and:
 - Git Bash works fine, however it renders many characters in a way that looks weird when it comes to the Tui, also dragging movable box around feels a little bit slow.
 - It seems like performance of `cmd`, or `Windows Terminal` has improved and it basically that of WSL

I'll need to check these things on Windows 10 though, because those things might've been improved in just Windows 11

**Comment by nhrones** [comment]
Thanks for the look.  Love TUI!

**Comment by Im-Beast** [comment]
Sorry, but this issue could still apply, check my previous message:
> I'll need to check these things on Windows 10 though, because those things might've been improved in just Windows 11

Documentation still needs to be adjusted either way, as performance on windows 11 seemed on pair with that of WSL

**Comment by Im-Beast** [comment]
Performance seems to have improved even on latest Windows 10, WSL isn't as neccessary for Tui as it once was. Thanks for this issue!

**Comment by nhrones** [comment]
I've had issues with WSL, so I cleaned up and use Git-Bash, and never looked back.  Also never any of issues that original WSL was causing.
Git bash works great as the default in VS Code. I can run all examples from Deno docs and blog posts without 'cmd' incompatibilities.
